#!/usr/bin/env bash
# Render ~/.config/opencode/opencode.json and ~/.opencode/.env.
# Two endpoints: OU AI Sandbox (first choice, if you have a key) and
# OpenRouter (your own key). The default model points at whichever endpoint
# preflight validated (or, before preflight has run, whichever key is present —
# OU Sandbox preferred). Override with OPENCODE_PROVIDER=litellm|openrouter.
# Usage: scripts/configure.sh [OPENROUTER_API_KEY]
#   Key is resolved as: $1  >  env vars  >  existing ~/.opencode/.env
# Idempotent: safe to run as many times as you like.
set -euo pipefail

# ---- Settings (override via env if your model/endpoint differ) ----
# Default OpenRouter model slug (used only when LITELLM_API_KEY is absent).
OPENROUTER_MODEL="${OPENROUTER_MODEL:-qwen/qwen3-coder}"
# OU AI Sandbox endpoint (first choice when you have a key).
LITELLM_BASE_URL="${LITELLM_BASE_URL:-https://litellm.lib.ou.edu}"
# NOTE: the id must match what the endpoint reports at /v1/models.
LITELLM_MODEL="${LITELLM_MODEL:-Qwen3 Coder 30B}"
# -----------------------------------------------------------------

STATE_DIR="${HOME}/.opencode"
CONFIG_DIR="${HOME}/.config/opencode"
CONFIG_FILE="${CONFIG_DIR}/opencode.json"
ENV_FILE="${STATE_DIR}/.env"
OR_PLACEHOLDER="sk-or-REPLACE_ME"
LL_PLACEHOLDER="sk-REPLACE_ME"

mkdir -p "${STATE_DIR}" "${CONFIG_DIR}"

# Make 'opencode' findable for the optional validation step below.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_env.sh"

# Resolve the OpenRouter key: explicit arg > env var > existing .env file.
OR_KEY="${1:-${OPENROUTER_API_KEY:-}}"
if [[ -z "${OR_KEY}" && -f "${ENV_FILE}" ]]; then
  OR_KEY="$(grep -E '^OPENROUTER_API_KEY=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
fi
[[ -z "${OR_KEY}" ]] && OR_KEY="${OR_PLACEHOLDER}"

# Optional OU AI Sandbox key — env var > existing .env file > placeholder.
LL_KEY="${LITELLM_API_KEY:-}"
if [[ -z "${LL_KEY}" && -f "${ENV_FILE}" ]]; then
  LL_KEY="$(grep -E '^LITELLM_API_KEY=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
fi
[[ -z "${LL_KEY}" ]] && LL_KEY="${LL_PLACEHOLDER}"

# Write ~/.opencode/.env (OpenCode reads this at startup).
umask 077
{
  printf '# Auto-generated by hermes-auto-start. Do NOT commit.\n'
  printf 'OPENROUTER_API_KEY=%s\n' "${OR_KEY}"
  printf 'LITELLM_API_KEY=%s\n' "${LL_KEY}"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

# Which endpoint should the default model use?
# OPENCODE_PROVIDER env > preflight's ~/.opencode/.provider > key presence
# (LiteLLM preferred — it's the course's first choice).
PROVIDER="${OPENCODE_PROVIDER:-}"
if [[ -z "${PROVIDER}" && -f "${STATE_DIR}/.provider" ]]; then
  PROVIDER="$(cat "${STATE_DIR}/.provider" 2>/dev/null || true)"
fi
if [[ -z "${PROVIDER}" ]]; then
  if [[ "${LL_KEY}" != "${LL_PLACEHOLDER}" ]]; then PROVIDER="litellm"; else PROVIDER="openrouter"; fi
fi

# Escape a string for use inside a JSON double-quoted value.
json_str() { printf '%s' "$1" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))[1:-1]' 2>/dev/null || printf '%s' "$1"; }

# Write ~/.config/opencode/opencode.json — OpenCode reads this on every startup.
umask 077
{
  printf '{\n'
  printf '  "$schema": "https://opencode.ai/config.json",\n'
  if [[ "${PROVIDER}" == "litellm" ]]; then
    # OU AI Sandbox: OpenAI-compatible custom endpoint.
    BASE_URL="${LITELLM_BASE_URL%/}/v1"
    printf '  "provider": {\n'
    printf '    "ou-sandbox": {\n'
    printf '      "npm": "@ai-sdk/openai-compatible",\n'
    printf '      "name": "OU AI Sandbox",\n'
    printf '      "options": {\n'
    printf '        "baseURL": "%s",\n' "${BASE_URL}"
    printf '        "apiKey": "%s"\n' "$(json_str "${LL_KEY}")"
    printf '      },\n'
    printf '      "models": {\n'
    printf '        "%s": { "name": "%s" }\n' "$(json_str "${LITELLM_MODEL}")" "$(json_str "${LITELLM_MODEL}")"
    printf '      }\n'
    printf '    }\n'
    printf '  },\n'
    printf '  "model": "ou-sandbox/%s"\n' "$(json_str "${LITELLM_MODEL}")"
  else
    # OpenRouter: built-in provider — key comes from OPENROUTER_API_KEY env var.
    printf '  "provider": {\n'
    printf '    "openrouter": {\n'
    printf '      "options": {\n'
    printf '        "apiKey": "%s"\n' "$(json_str "${OR_KEY}")"
    printf '      }\n'
    printf '    }\n'
    printf '  },\n'
    printf '  "model": "openrouter/%s"\n' "$(json_str "${OPENROUTER_MODEL}")"
  fi
  printf '}\n'
} > "${CONFIG_FILE}"
chmod 600 "${CONFIG_FILE}"

if [[ "${PROVIDER}" == "litellm" ]]; then
  echo "Wrote ${CONFIG_FILE} (default model: ${LITELLM_MODEL}; OU AI Sandbox: ${LITELLM_BASE_URL})"
else
  echo "Wrote ${CONFIG_FILE} (default model: ${OPENROUTER_MODEL}; provider: OpenRouter)"
fi

if [[ "${OR_KEY}" == "${OR_PLACEHOLDER}" && "${LL_KEY}" == "${LL_PLACEHOLDER}" ]]; then
  echo "!! No endpoint key found — wrote placeholders."
  echo "   Provide your OU AI Sandbox key (issued by the course), or create your"
  echo "   own OpenRouter key at https://openrouter.ai (Settings → Keys). Then run"
  echo "   'bash scripts/set-key.sh' or set the matching Codespaces secret."
fi

# Best-effort validation if OpenCode is already installed.
if command -v opencode >/dev/null 2>&1; then
  opencode --version >/dev/null 2>&1 \
    && echo "OpenCode is available: $(opencode --version 2>/dev/null)." \
    || echo "(Heads up: 'opencode' is not responding — run 'bash scripts/install-opencode.sh'.)"
fi

