#!/usr/bin/env bash
# Render ~/.hermes/config.yaml and ~/.hermes/.env.
# Two endpoints: OU AI Sandbox (first choice, if you have a key) and
# OpenRouter (your own key). The default model points at whichever endpoint
# preflight validated (or, before preflight has run, whichever key is present —
# OU Sandbox preferred). Override with HERMES_PROVIDER=litellm|openrouter.
# Usage: scripts/configure.sh [OPENROUTER_API_KEY]
#   Key is resolved as: $1  >  env vars  >  existing ~/.hermes/.env
# Idempotent: safe to run as many times as you like.
set -euo pipefail

# ---- Settings (override via env if your model/endpoint differ) ----
# Default OpenRouter model slug (used only when LITELLM_API_KEY is absent).
# Verify the current slug at https://openrouter.ai/models before the term.
OPENROUTER_MODEL="${OPENROUTER_MODEL:-qwen/qwen3-coder}"
# Optional comma-separated fallback (secondary) model slugs (same provider).
OPENROUTER_MODEL_FALLBACKS="${OPENROUTER_MODEL_FALLBACKS:-}"
# OU AI Sandbox endpoint (first choice when you have a key).
LITELLM_BASE_URL="${LITELLM_BASE_URL:-https://litellm.lib.ou.edu}"
# NOTE: the id must match what the endpoint reports at /v1/models.
LITELLM_MODEL="${LITELLM_MODEL:-Qwen3 Coder 30B}"
# -----------------------------------------------------------------

STATE_DIR="${HOME}/.hermes"
CONFIG_FILE="${STATE_DIR}/config.yaml"
ENV_FILE="${STATE_DIR}/.env"
OR_PLACEHOLDER="sk-or-REPLACE_ME"
LL_PLACEHOLDER="sk-REPLACE_ME"

mkdir -p "${STATE_DIR}"

# Make 'hermes' findable for the optional validation step below.
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_env.sh"

# Resolve the OpenRouter key: explicit arg > env var > existing .env file.
OR_KEY="${1:-${OPENROUTER_API_KEY:-}}"
if [[ -z "${OR_KEY}" && -f "${ENV_FILE}" ]]; then
  OR_KEY="$(grep -E '^OPENROUTER_API_KEY=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
fi
[[ -z "${OR_KEY}" ]] && OR_KEY="${OR_PLACEHOLDER}"

# Optional OU AI Sandbox key — env var > existing .env file > placeholder.
LL_KEY="${LITELLM_API_KEY:-}"
if [[ -z "${LL_KEY}" && -f "${ENV_FILE}" ]]; then
  LL_KEY="$(grep -E '^LITELLM_API_KEY=' "${ENV_FILE}" | tail -n1 | cut -d= -f2- || true)"
fi
[[ -z "${LL_KEY}" ]] && LL_KEY="${LL_PLACEHOLDER}"

# Write ~/.hermes/.env (OpenRouter key — Hermes reads this automatically).
umask 077
{
  printf '# Auto-generated by hermes-auto-start. Do NOT commit.\n'
  printf 'OPENROUTER_API_KEY=%s\n' "${OR_KEY}"
  printf 'LITELLM_API_KEY=%s\n' "${LL_KEY}"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

# Which endpoint should the default model use?
# HERMES_PROVIDER env > preflight's ~/.hermes/.provider > key presence
# (LiteLLM preferred — it's the course's first choice).
PROVIDER="${HERMES_PROVIDER:-}"
if [[ -z "${PROVIDER}" && -f "${STATE_DIR}/.provider" ]]; then
  PROVIDER="$(cat "${STATE_DIR}/.provider" 2>/dev/null || true)"
fi
if [[ -z "${PROVIDER}" ]]; then
  if [[ "${LL_KEY}" != "${LL_PLACEHOLDER}" ]]; then PROVIDER="litellm"; else PROVIDER="openrouter"; fi
fi

# Write ~/.hermes/config.yaml — Hermes reads this on every startup.
umask 077
{
  printf '# Auto-generated by hermes-auto-start scripts/configure.sh. Do NOT commit.\n'
  printf '# Edit settings with: hermes config set <key> <value>\n'
  printf '# or run: bash scripts/select-model.sh  to switch models interactively.\n'
  printf 'model:\n'
  if [[ "${PROVIDER}" == "litellm" ]]; then
    # OU AI Sandbox: OpenAI-compatible custom endpoint.
    # base_url takes precedence over provider; api_key authenticates the call.
    printf '  base_url: "%s/v1"\n' "${LITELLM_BASE_URL%/}"
    printf '  api_key: "%s"\n' "${LL_KEY}"
    printf '  default: "%s"\n' "${LITELLM_MODEL}"
  else
    # OpenRouter: native provider — key comes from OPENROUTER_API_KEY in .env.
    printf '  provider: openrouter\n'
    printf '  default: "%s"\n' "${OPENROUTER_MODEL}"
  fi
} > "${CONFIG_FILE}"
chmod 600 "${CONFIG_FILE}"

if [[ "${PROVIDER}" == "litellm" ]]; then
  echo "Wrote ${CONFIG_FILE} (default model: ${LITELLM_MODEL}; OU AI Sandbox: ${LITELLM_BASE_URL})"
else
  echo "Wrote ${CONFIG_FILE} (default model: ${OPENROUTER_MODEL}; provider: OpenRouter)"
fi

if [[ "${OR_KEY}" == "${OR_PLACEHOLDER}" && "${LL_KEY}" == "${LL_PLACEHOLDER}" ]]; then
  echo "!! No endpoint key found — wrote placeholders."
  echo "   Provide your OU AI Sandbox key (issued by the course), or create your"
  echo "   own OpenRouter key at https://openrouter.ai (Settings → Keys). Then run"
  echo "   'bash scripts/set-key.sh' or set the matching Codespaces secret."
fi

# Best-effort validation if Hermes is already installed.
if command -v hermes >/dev/null 2>&1; then
  hermes doctor --quiet >/dev/null 2>&1 \
    && echo "Config validated OK (hermes doctor)." \
    || echo "(Heads up: 'hermes doctor' reported issues — run it directly to inspect.)"
fi

